### ISSUE TITLE
How do I get a zip archive with the compiled plugin?

### ISSUE THREAD

**Issue by vicneanschi** [simoneb/TeamCity-TargetProcess#1]
I don't know how to build this plugin. Could you share a built version for TC 9.1.x?
Thanks

**Comment by simoneb** [comment]
You can build the plugin using IntelliJ Idea

**Comment by vicneanschi** [comment]
I suspected that it should be built. Could you publish built zip somewhere please?

**Comment by simoneb** [comment]
I'm sorry, building it is very simple you should be able to do it.

**Comment by vicneanschi** [comment]
I was trying to build it using IntelliJ Idea. 
I have TeamCity 9.1.5 installed on the machine. 
JDK 1.8.

> Error:(28, 5) java: constructor AbstractIssueProviderFactory in class jetbrains.buildServer.issueTracker.AbstractIssueProviderFactory cannot be applied to given types;
>   required: jetbrains.buildServer.issueTracker.IssueProviderType,jetbrains.buildServer.issueTracker.IssueFetcher
>   found: jetbrains.buildServer.issueTracker.IssueFetcher,java.lang.String,java.lang.String
>   reason: actual and formal argument lists differ in length

**Comment by simoneb** [comment]
I'm afraid the problem might be a change in the TeamCity API. I wrote this against 9.x (< 9.1). It looks like the API has changed in 9.1 and the code has to be changed. No idea what has changed and how to adapt the code though.

**Comment by vicneanschi** [comment]
9.1 must be compatible with 9.x though. Anyway thanks.

**Comment by simoneb** [comment]
It isn't: https://confluence.jetbrains.com/display/TCD9/Open+API+Changes

**Comment by vicneanschi** [comment]
Oh. Indeed. I see what you mean. Would you have time to make it work with
9.1?

Or maybe you could point me to another plugin for TargetProcess integration.

Thanks
